pipeline {
    agent any
    tools {
        // Define the Maven installation from Jenkins configuration
        maven 'Maven'
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your SCM
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                // Build the Maven project using Windows batch command                
                dir('testwebap') {
                    bat 'mvn clean package'
                }

            }
        }
        
        stage('Test') {
            steps {
                // Run tests (if any) using Windows batch command
                dir('testwebap') {
                    bat 'mvn test'
                }
            }
        }      
    }
}
